[build]
  publish = "public"
  command = "echo 'Using static HTML files from public folder'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "python -m http.server 8080 --directory public"
  port = 8080
  publish = "public"
